pipeline{
    agent any

    stages{
        stage('Server deatils'){
            steps{
                echo "We are printing server deatils"

            }
        }
        stage('Hostname'){
            steps{
                sh "hostname"
            }
        }
        stage("IP Address"){
            steps{
                sh "hostname -I"
            }
        }
        stage('Listing CPU details'){
            steps{
                sh "lscpu"
            }

        }
        stage('Memory usage'){
            steps{
                sh "free -h"
            }
        }
    }
pipeline{
    agent any

    stages{
        stage('Server deatils'){
            steps{
                echo "We are printing server deatils"

            }
        }
        stage('Hostname'){
            steps{
                sh "hostname"
            }
        }
        stage("IP Address"){
            steps{
                sh "hostname -I"
            }
        }
        stage('Listing CPU details'){
            steps{
                sh "lscpu"
            }

        }
        stage('Memory usage'){
            steps{
                sh "free -h"
            }
        }
        stage('Disk Utilization'){
            steps{
                sh "df -h"
            }
        }
    }
}
